version: '3.8'

services:
  monomap:
    image: juanpahv/monomap-api:latest
    environment:
      PORT: ${PORT}
      MONGO_URL_DOCKER: ${MONGO_URL_DOCKER}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      MAILER_ACCESS_TOKEN: ${MAILER_ACCESS_TOKEN}
      MAILER_SERVICE: ${MAILER_SERVICE}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-monomap
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
